#!/bin/bash
# Verify that password logins are disabled for ssh
#
count=$(grep -c "^PasswordAuthentication no$" /etc/ssh/sshd_config)
if [ $count -gt 0 ] ; then
    status=0
    statustxt=OK
    sshconfig=disabled
else
    status=1
    statustxt=WARNING
    sshconfig=enabled
fi
echo "$status SSH_Password_Logins - $statustxt - Password logins over SSH are $sshconfig"
