#!/usr/bin/env python

"""
MN-CN PID disparity list generator
Compare the objects held by a Member Node with the objects known to a
Coordinating Node, and report identifiers that are present on the MN but
have not yet been synchronized to the CN.
"""

import argparse
import logging
import sys

import d1_client.cnclient_2_0
import d1_client.mnclient_2_0
import d1_common.env
import d1_common.node
import d1_common.types.exceptions

PAGE_SIZE = 1000


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--env",
        type=str,
        default="prod",
        help="Environment, one of {}".format(", ".join(d1_common.env.D1_ENV_DICT)),
    )
    parser.add_argument(
        "mn_id", help="NodeId of the Member Node to check, e.g. urn:node:XXXX"
    )
    parser.add_argument(
        "--mn-base-url",
        dest="mn_base_url",
        default=None,
        help="Base URL of the Member Node (looked up from the CN if not provided)",
    )
    parser.add_argument(
        "--cert-pub",
        dest="cert_pem_path",
        default=None,
        help="Path to PEM formatted public key of certificate",
    )
    parser.add_argument(
        "--cert-key",
        dest="cert_key_path",
        default=None,
        help="Path to PEM formatted private key of certificate",
    )
    parser.add_argument(
        "-o", "--out", dest="out_path", default=None,
        help="File to write the list of unsynced identifiers to (default: stdout)",
    )
    parser.add_argument("--debug", action="store_true", help="Debug level logging")
    args = parser.parse_args()

    log_setup(is_debug=args.debug)

    try:
        d1env_dict = d1_common.env.D1_ENV_DICT[args.env]
    except LookupError:
        raise SystemExit(
            "Environment must be one of {}".format(", ".join(d1_common.env.D1_ENV_DICT))
        )

    cn_client = d1_client.cnclient_2_0.CoordinatingNodeClient_2_0(
        d1env_dict["base_url"],
        cert_pem_path=args.cert_pem_path,
        cert_key_path=args.cert_key_path,
    )

    mn_base_url = args.mn_base_url
    if mn_base_url is None:
        node_dict = d1_common.node.pyxb_to_dict(cn_client.listNodes())
        try:
            mn_base_url = node_dict[args.mn_id]["base_url"]
        except LookupError:
            raise SystemExit(
                "NodeId '{}' not found in CN node list and --mn-base-url not "
                "provided".format(args.mn_id)
            )

    mn_client = d1_client.mnclient_2_0.MemberNodeClient_2_0(
        mn_base_url,
        cert_pem_path=args.cert_pem_path,
        cert_key_path=args.cert_key_path,
    )

    logging.info("Retrieving identifiers from MN {} ({})".format(args.mn_id, mn_base_url))
    mn_pid_set = get_all_pids(mn_client)
    logging.info("MN has {} identifiers".format(len(mn_pid_set)))

    logging.info("Retrieving identifiers known to CN for nodeId={}".format(args.mn_id))
    cn_pid_set = get_all_pids(cn_client, node_id=args.mn_id)
    logging.info("CN has {} identifiers for this MN".format(len(cn_pid_set)))

    unsynced = sorted(mn_pid_set - cn_pid_set)
    logging.info("{} identifiers on MN are not yet on CN".format(len(unsynced)))

    out = sys.stdout
    if args.out_path is not None:
        out = open(args.out_path, "w")
    try:
        for pid in unsynced:
            out.write(pid + "\n")
    finally:
        if out is not sys.stdout:
            out.close()

    return 0


def get_all_pids(client, node_id=None):
    """
  Page through listObjects() and return the set of all identifiers returned.

  :param client: a MemberNodeClient_2_0 or CoordinatingNodeClient_2_0 instance
  :param node_id: optional nodeId filter, passed to CN listObjects
  :return: set of identifier strings
  """
    pid_set = set()
    start = 0
    total = None
    kwparams = {}
    if node_id is not None:
        kwparams["nodeId"] = node_id
    while total is None or start < total:
        try:
            response = client.listObjects(start=start, count=PAGE_SIZE, **kwparams)
        except d1_common.types.exceptions.DataONEException as e:
            logging.error("listObjects failed: {}".format(e))
            break
        total = response.total
        for entry in response.objectInfo:
            pid_set.add(entry.identifier.value().strip())
        start += response.count
        if response.count == 0:
            break
    return pid_set


def log_setup(is_debug=False):
    formatter = logging.Formatter(
        "%(asctime)s %(levelname)-8s %(message)s", "%Y-%m-%d %H:%M:%S"
    )
    console_logger = logging.StreamHandler(sys.stderr)
    console_logger.setFormatter(formatter)
    logging.getLogger("").addHandler(console_logger)
    logging.getLogger("").setLevel(logging.DEBUG if is_debug else logging.INFO)


if __name__ == "__main__":
    sys.exit(main())
