#!/bin/env python

'''
Delete an entry from a DataONE environment.

This operation should be used with caution and only when requested by a Member Node operator and there is a
good reason to delete the content.

The delete operation can only be run by a user authenticated as a CN administrator. A successful completion of the
operation will remove all copies of the content (including replicas), and remove the entry from the search index. The
identifier will remain in the system and can not be reused.

'''

'''
TODO: investigate why successful delete in production did not clear the entry form the search index.

cn-orc-1:/var/log/dataone/index$ grep -r "seadva-e056e535-da57-40c0-90c1-c2e55d2ec573" *
cn-index-generator-daemon.log:[ INFO] 2016-11-08 16:07:24,382 (IndexTaskGeneratorEntryListener:entryRemoved:133) REMOVE EVENT - index task generator - system metadata callback invoked on pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573
cn-index-generator-daemon.log.10:[ INFO] 2016-09-25 00:22:54,467 (IndexTaskGeneratorEntryListener:entryAdded:100) ADD EVENT - index task generator - system metadata callback invoked on pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573
cn-index-generator-daemon.log.10:[ INFO] 2016-09-25 00:22:54,468 (IndexTaskGeneratorEntryListener:entryAdded:108) Processing add event index task for pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573
cn-index-generator-daemon.log.10:[ INFO] 2016-09-25 00:22:55,257 (IndexTaskGeneratorEntryListener:entryRemoved:133) REMOVE EVENT - index task generator - system metadata callback invoked on pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573
cn-index-generator-daemon.log.6:[ INFO] 2016-09-29 23:01:42,612 (IndexTaskGeneratorEntryListener:entryAdded:100) ADD EVENT - index task generator - system metadata callback invoked on pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573
cn-index-generator-daemon.log.6:[ INFO] 2016-09-29 23:01:42,612 (IndexTaskGeneratorEntryListener:entryAdded:108) Processing add event index task for pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573
cn-index-generator-daemon.log.6:[ INFO] 2016-09-29 23:02:16,284 (IndexTaskGeneratorEntryListener:entryUpdated:87) UPDATE EVENT - index task generator - system metadata callback invoked on pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573
cn-index-generator-daemon.log.6:[ INFO] 2016-09-29 23:02:19,286 (IndexTaskGeneratorEntryListener:entryUpdated:87) UPDATE EVENT - index task generator - system metadata callback invoked on pid: seadva-e056e535-da57-40c0-90c1-c2e55d2ec573

'''
import sys
import codecs
import logging
import argparse
import pprint
import d1_admin_tools
from d1_admin_tools import operations
import d1_common
from d1_client import cnclient_2_0


def presentBefore(environment, pid, res):
  print(("Request to delete identifier {0} from the {1} environment".format(pid, environment)))
  print("Resolve status before delete:")
  pprint.pprint(res['before'], indent=2)


def doDelete(client, pid):
  results = {}
  logging.warn("DELETE: %s", pid)
  response = client.deleteObjectResponse(pid)
  results = {'result': client._read_dataone_type_response(response, 'Identifier'),
             'status': response.status_code}
  return results


def main():
  parser = argparse.ArgumentParser(description=__doc__,
    formatter_class=argparse.RawDescriptionHelpFormatter)
  parser.add_argument('-E', '--certificate',
                      default=None,
                      help='Certificate to authenticate request.')
  parser.add_argument('-b','--batch', action='store_true', default=False,
                      help='Batch mode - provide file name with one pid per line instead of PID argument')
  parser.add_argument('pid',
                      help="Identifier to delete")
  args, config = d1_admin_tools.defaultScriptMain(parser)
  logger = logging.getLogger('main')

  #if not os.path.exists(args.certificate):
  #  logger.error("Certificate not found: %s", args.certificate)
  #  return 1

  env_nodes = config.envNodes(args.environment)
  client = env_nodes.getClient(cert_pem_path=args.certificate)
  pids = [args.pid ]
  if args.batch:
    pids = []
    with codecs.open(args.pid, 'r', encoding='UTF-8') as pid_file:
      for pid in pid_file:
        pid = pid.strip()
        if len(pid) > 0:
          pids.append(pid)
    print("")
    print(("About to DELETE content for {0} identifiers from the {1} environment.".format(len(pids), args.environment)))
    affirmation = input("Please confirm DELETE (yes or no):")
    if affirmation != 'yes':
      raise ValueError("Terminating DELETE request.")

  for pid in pids:
    results = {}
    results['pid'] = pid
    results['environment'] = args.environment
    logging.info("Resolving identifier before delete: %s", pid)
    results['before'] = operations.resolve(client, pid)
    presentBefore(args.environment, pid, results)
    if results['before']['status']['msg'] == 'OK':
      if not args.batch:
        print("")
        print(("About to DELETE content for identifier {0} from the {1} environment.".format(pid, args.environment)))
        affirmation = input("Please confirm DELETE (yes or no):")
        if affirmation != 'yes':
          raise ValueError("Terminating DELETE request.")

      results['delete'] = doDelete(client, pid)
      if results['delete']['status'] == 200:
        logger.info("SUCCESS: Identifier %s deleted from the %s environment.", pid, args.environment)

      logging.info("Resolving identifier after delete: %s", pid)
      results['after'] = operations.resolve(client, pid)
      print("")
      print("Return from delete operation:")
      pprint.pprint(results['delete'], indent=2)

      print("")
      print("Resolve results after delete:")
      pprint.pprint(results['after'], indent=2)
    else:
      logging.info("Ignoring request to delete %s because it could not be resolved.", pid)
  return 0


if __name__ == "__main__":
  sys.exit(main())