#!/bin/env python

"""
List facet values from solr
"""

import sys
import logging
import argparse
import d1_admin_tools
from d1_admin_tools import dataone_response
from d1_client import d1baseclient_2_0
import datetime
import dateparser

DATE_FORMAT = "%Y-%m-%dT%H:%M:%S+00:00"

def doListObjects(base_url, *params, **kvparams):
  client = d1baseclient_2_0.DataONEBaseClient_2_0(base_url, capture_response_body=True)
  response = client.listObjects(*params, **kvparams)
  return dataone_response.DataONEResponse( obj=response )


def main():
  '''
  -c --config:      optional path to configuration
  -e --environment: name of environment
  -f --format:      name of output format
  -l --log_level:   flag to turn on logging, more means more detailed logging.

  :return: int for sys.exit()
  '''
  parser = argparse.ArgumentParser(description='Call list objects on a CN or MN.')
  parser.add_argument('-B', '--base_url',
                      default=None,
                      help='Base URL of node to connect with (overrides -e)')
  parser.add_argument('-i', '--identifiers',
                      default=False,
                      action='store_true',
                      help='Output only PIDs')
  parser.add_argument('-p', '--page_size',
                      default=10,
                      help='Page size to return')
  parser.add_argument('-s', '--start_index',
                      default=0,
                      help='Zero based index of first entry')
  parser.add_argument('-C', '--max_records',
                      default=5,
                      help='Maximum number of entries to retrieve.')
  args, config = d1_admin_tools.defaultScriptMain(parser)
  base_url = args.base_url
  if base_url is None:
    base_url = config.envPrimaryBaseURL(args.environment)
  logging.info("Base URL = %s", base_url)
  n_retrieved = 0
  if int(args.page_size) > int(args.max_records):
    args.page_size = int(args.max_records)
  max_to_retrieve = int(args.max_records)
  start_index = args.start_index
  total_records = -1
  counter = start_index
  while n_retrieved < max_to_retrieve:
    res = doListObjects(base_url,
                        count = args.page_size,
                        start = start_index)
    if total_records < 0:
      total_records = int(res.content.total)
      if max_to_retrieve > total_records:
        max_to_retrieve = total_records

    n_retrieved += res.content.count
    start_index = res.content.start + res.content.count
    if args.format == 'xml':
      print res.asXML()
    else:
      for entry in res.content.objectInfo:
        data = {'counter': counter,
                'size':entry.size,
                'date_modified': entry.dateSysMetadataModified.strftime(DATE_FORMAT),
                'pid': entry.identifier.value(),
                'format_id':entry.formatId}
        print "{counter:0>6}: {size:<9} {date_modified:<25} {pid:<50} {format_id}".format(**data)
        counter += 1
  return 0


if __name__ == '__main__':
  sys.exit( main() )