#!/bin/env python

"""
List facet values from solr
"""

import sys
import logging
import argparse
import d1_admin_tools
from d1_admin_tools import dataone_response
from d1_client import d1baseclient_2_0


def doListObjects(base_url, *params, **kvparams):
  client = d1baseclient_2_0.DataONEBaseClient_2_0(base_url, capture_response_body=True)
  response = client.listObjects(*params, **kvparams)
  return dataone_response.DataONEResponse( obj=response )


def main():
  '''
  -c --config:      optional path to configuration
  -e --environment: name of environment
  -f --format:      name of output format
  -l --log_level:   flag to turn on logging, more means more detailed logging.

  :return: int for sys.exit()
  '''
  parser = argparse.ArgumentParser(description='Call list objects on a CN or MN.')
  parser.add_argument('-B', '--base_url',
                      default=None,
                      help='Base URL of node to connect with (overrides -e)')
  parser.add_argument('-i', '--identifiers',
                      default=False,
                      action='store_true',
                      help='Output only PIDs')
  parser.add_argument('-p', '--page_size',
                      default=3,
                      help='Page size to return')
  parser.add_argument('-s', '--start_index',
                      default=0,
                      help='Zero based index of first entry')


  args, config = d1_admin_tools.defaultScriptMain(parser)
  base_url = args.base_url
  if base_url is None:
    base_url = config.envPrimaryBaseURL(args.environment)
  logging.info("Base URL = %s", base_url)
  res = doListObjects(base_url,
                      count = args.page_size,
                      start = args.start_index)
  print res.asXML()

if __name__ == '__main__':
  sys.exit( main() )