#!/usr/bin/env python
'''
Retrieve system metadata for a PID
'''

import logging
import argparse
import d1_admin_tools
from d1_admin_tools import dataone_response
from d1_client import d1baseclient_2_0


def getSystemMetadata(client, pid):
  ''' Retrieve system metadata for a PID

  :param client: An instance of CoordinatingNodeClient
  :param pid: Identifier to resolve
  :return: Dictionary mimicking a SystemMetadata structure with addition of error entry
  '''
  try:
    res = client.getSystemMetadata(pid)
    return dataone_response.DataONEResponse( obj=res )
  except Exception as e:
    logging.info(e)
  return dataone_response.DataONEResponse( e )


def main():
  '''
  -c --config:      optional path to configuration
  -e --environment: name of environment
  -f --format:      name of output format
  -l --log_level:   flag to turn on logging, more means more detailed logging.

  :return: int for sys.exit()
  '''
  parser = argparse.ArgumentParser(description='Resolve identifier in a DataONE environment.')
  parser.add_argument('-B', '--baseURL',
                      default="https://cn.dataone.org/cn",
                      help='Base URL of node from which to retrieve system metadata (overrides -e)')
  parser.add_argument('pid',
                      help="Identifier to evaluate")
  defaults = {'format': ['text', 'json', 'xml'],
              }
  args, config = d1_admin_tools.defaultScriptMain(parser, defaults)
  pid = args.pid
  base_url = args.baseURL
  client = d1baseclient_2_0.DataONEBaseClient_2_0(base_url, capture_response_body=True)
  results = getSystemMetadata(client, pid)
  format = args.format.lower()
  if format not in defaults['format']:
    format = 'text'
  if args.format == 'xml':
    print( results.asXML() )
  elif args.format == 'json':
    print( results.asJSON())
  else:
    print( unicode(results) )


if __name__ == "__main__":
  main()
